
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author labib
 */
public class Customer extends javax.swing.JPanel {

    /**
     * Creates new form Customer
     */
    public Customer(String nama,String harga,String toko,String alamat, String foto) {
        initComponents();
        txtNamaBarang.setText(nama);
        txtUkuran.setText("Rp"+harga);
        txtToko.setText(toko);
        txtAlamat.setText(alamat); 
        BufferedImage fileImg = null;
        File photo = new File("src/images/" + foto);
        try {
            fileImg = ImageIO.read(photo);
            int width = labelImage.getWidth(), height = labelImage.getHeight();
            if(width == 0){
                width = 190;
            }
            if(height == 0){
                height = 160;
            }
            Image imagePhoto = fileImg.getScaledInstance(width, height,Image.SCALE_SMOOTH);
            ImageIcon imageIcon = new ImageIcon(imagePhoto);
            labelImage.setIcon(imageIcon);
        } catch (IOException ex) {
            Logger.getLogger(Beranda.class.getName()).log(Level.SEVERE, null, ex);
        }        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        labelImage = new javax.swing.JLabel();
        txtNamaBarang = new javax.swing.JLabel();
        txtUkuran = new javax.swing.JLabel();
        txtToko = new javax.swing.JLabel();
        txtAlamat = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(29, 28, 33));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(labelImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 160));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 160));

        txtNamaBarang.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 12)); // NOI18N
        txtNamaBarang.setForeground(new java.awt.Color(255, 255, 255));
        txtNamaBarang.setText("Kemeja Pria");
        jPanel1.add(txtNamaBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        txtUkuran.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 10)); // NOI18N
        txtUkuran.setForeground(new java.awt.Color(255, 0, 0));
        txtUkuran.setText("M");
        jPanel1.add(txtUkuran, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        txtToko.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 10)); // NOI18N
        txtToko.setForeground(new java.awt.Color(128, 128, 128));
        txtToko.setText("ADSDAD");
        jPanel1.add(txtToko, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        txtAlamat.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 10)); // NOI18N
        txtAlamat.setForeground(new java.awt.Color(128, 128, 128));
        txtAlamat.setText("Jawa Barat");
        jPanel1.add(txtAlamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-9, -4, 200, 270));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labelImage;
    private javax.swing.JLabel txtAlamat;
    private javax.swing.JLabel txtNamaBarang;
    private javax.swing.JLabel txtToko;
    private javax.swing.JLabel txtUkuran;
    // End of variables declaration//GEN-END:variables
}
