
import com.mysql.jdbc.PreparedStatement;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.StandardCopyOption;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author labib
 */
public class FormUpdate extends javax.swing.JFrame {

    /**
     * Creates new form FormSeller
     */
    private Config db;
    private String selectedID = "";
    private String photo;
    String ImagePath = null;
    private File selectFile;
    private File linkFile = null;
    private File dirFile = null;      
    private Beranda HomeSeller;
    private Boolean updateImage = false;
    public FormUpdate(Beranda HomeSeller,String id,String nama,String harga,String rating,String terjual,String foto) {
        initComponents();
        this.selectedID = id;
        this.photo = foto;
        this.HomeSeller = HomeSeller;
        txtId.setText(id);
        txtNama.setText(nama);
        txtHarga.setText(harga);   
        spinnerRating.setValue(Float.valueOf(rating));
        spinnerTerjual.setValue(Integer.valueOf(terjual));    
        db = new Config();
        jLabelImage.setText("src/images/" + foto);
        BufferedImage fileImg = null;
        File img = new File("src/images/" + foto);
        try {
            fileImg = ImageIO.read(img);
            int width = labelImage.getWidth(), height = labelImage.getHeight();
            if(width == 0){
                width = 115;
            }
            if(height == 0){
                height = 139;
            }
            Image image = fileImg.getScaledInstance(width, height,Image.SCALE_SMOOTH);
            ImageIcon ic = new ImageIcon(image);
            labelImage.setIcon(ic);
        } catch (IOException ex) {
            Logger.getLogger(Beranda.class.getName()).log(Level.SEVERE, null, ex);
        }
        buttonBack.setFocusPainted( false );
        buttonBack.setContentAreaFilled(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        buttonBack = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        spinnerRating = new javax.swing.JSpinner();
        txtHarga = new javax.swing.JTextField();
        txtNama = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        spinnerTerjual = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabelImage = new javax.swing.JLabel();
        Choose = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        labelImage = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(29, 28, 33));

        jLabel1.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Form Update");

        buttonBack.setBackground(new java.awt.Color(28, 28, 33));
        buttonBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vector.png"))); // NOI18N
        buttonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(buttonBack, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(99, 99, 99)
                .addComponent(jLabel1)
                .addContainerGap(144, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(buttonBack, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel1)))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel3.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(178, 178, 178));
        jLabel3.setText("Terjual");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 540, -1, -1));

        jLabel4.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(178, 178, 178));
        jLabel4.setText("Nama");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, -1, -1));

        spinnerRating.setModel(new javax.swing.SpinnerNumberModel(0.0f, null, 5.0f, 0.1f));
        jPanel1.add(spinnerRating, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 500, 280, -1));

        txtHarga.setBackground(new java.awt.Color(29, 28, 33));
        txtHarga.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(txtHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 280, -1));

        txtNama.setBackground(new java.awt.Color(29, 28, 33));
        txtNama.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(txtNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 280, -1));

        jLabel6.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(178, 178, 178));
        jLabel6.setText("Rating");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, -1, -1));

        jLabel5.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(178, 178, 178));
        jLabel5.setText("Harga");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, -1, -1));

        txtId.setBackground(new java.awt.Color(29, 28, 33));
        txtId.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 280, -1));
        jPanel1.add(spinnerTerjual, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 560, 280, -1));

        jLabel7.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(178, 178, 178));
        jLabel7.setText("Id");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, -1));

        jButton1.setBackground(new java.awt.Color(0, 153, 153));
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 610, -1, -1));

        jLabelImage.setForeground(new java.awt.Color(255, 255, 255));
        jLabelImage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.add(jLabelImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, 190, 30));

        Choose.setText("Choose");
        Choose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChooseActionPerformed(evt);
            }
        });
        jPanel1.add(Choose, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(labelImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 150));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 150, 150));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login (2).png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 46, 390, 610));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 391, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBackActionPerformed
        // TODO add your handling code here:
        this.dispose();
        HomeSeller.setPanel();    
    }//GEN-LAST:event_buttonBackActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:        
        int confirmationPrompt = JOptionPane.showConfirmDialog(this,"Anda yakin ingin mengubah data?", "Select Delete Option", JOptionPane.YES_NO_OPTION);
        if(confirmationPrompt == JOptionPane.YES_OPTION){
            String namaBarang = txtNama.getText();
            String selectHarga = txtHarga.getText();
            String selectRating = Float.toString((float) spinnerRating.getValue());
            String selectTerjual = Integer.toString((int) spinnerTerjual.getValue());
            if(updateImage == true){
                String PathFile = "src/images";
                File direk = new File(PathFile);
                if (!direk.exists()) {
                    direk.mkdirs();
                }
                if(selectFile != null){
                    String namaFile = selectFile.getName();
                    System.out.println(namaFile);
                    linkFile = new File(ImagePath);
                    System.out.println(linkFile.toString());
                    dirFile = new File(PathFile +"/"+ namaFile);
                    System.out.println(dirFile.toString());
                    try {
                        Files.copy(linkFile.toPath(), dirFile.toPath(), StandardCopyOption.REPLACE_EXISTING);
                    } catch (IOException ex) {
                        Logger.getLogger(FormSeller.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }else{
                    JOptionPane.showMessageDialog(null, "Data belum lengkap!");
                }
            }
            else{
                dirFile = new File("src/images/" + photo);
            }
            if(!namaBarang.isEmpty() && !selectHarga.isEmpty() && !selectRating.isEmpty() && !selectTerjual.isEmpty()  && dirFile != null){
                String foto = dirFile.toString();
                foto = foto.replace("\\", "\\\\");
                String sql2 = "UPDATE seller SET name='" + namaBarang + "', harga='" + selectHarga + "', rating='" + selectRating + "', terjual='" + selectTerjual + "', foto='" + foto + "' WHERE id='" + selectedID +"'";
                db.updateQuery(sql2);

                System.out.println("Update Success!");
                JOptionPane.showMessageDialog(null, "Data berhasil diubah");
                this.dispose();
                this.HomeSeller.setPanel();
            } 
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ChooseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChooseActionPerformed
        updateImage= true;
        try{
            JFileChooser Chooser = new JFileChooser();
            Chooser.setCurrentDirectory(new File(System.getProperty("user.home")));
            int photo = Chooser.showOpenDialog(null);
  
            if (photo == JFileChooser.APPROVE_OPTION) {
                selectFile = Chooser.getSelectedFile();
                ImagePath = selectFile.getAbsolutePath();
                BufferedImage bi = ImageIO.read(new File(ImagePath));
                Image foto = bi.getScaledInstance(150,150, Image.SCALE_SMOOTH);
                ImageIcon imageIcon = new ImageIcon(foto);                
                labelImage.setIcon(imageIcon);
                jLabelImage.setText(ImagePath);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Gagal Upload");
        }
            
    }//GEN-LAST:event_ChooseActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Choose;
    private javax.swing.JButton buttonBack;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelImage;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel labelImage;
    private javax.swing.JSpinner spinnerRating;
    private javax.swing.JSpinner spinnerTerjual;
    private javax.swing.JTextField txtHarga;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNama;
    // End of variables declaration//GEN-END:variables
}
