
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;
import javax.swing.JOptionPane;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author labib
 */
public class Seller extends javax.swing.JPanel {

    /**
     * Creates new form Customer
     */
    private Config db;
    private String selectedID = "";
    private String nama;
    private String harga;
    private String rating;
    private String terjual;
    private String foto;
    private Beranda home;
    
    public Seller(Beranda home,String selectedID,String nama,String harga,String rating,String terjual, String foto) {
        initComponents();
        db  = new Config();
        this.selectedID = selectedID;
        this.nama = nama;
        this.harga = harga;
        this.rating = rating;
        this.terjual = terjual;
        this.foto = foto;
        this.home = home;
        txtNamaBarang.setText(nama);
        txtHarga.setText("Rp"+harga);
        txtRating.setText(rating);
        txtTerjual.setText(terjual);
        BufferedImage fileImg = null;
        File img = new File("src/images/" + foto);
        try {
            fileImg = ImageIO.read(img);
            int width = labelImage.getWidth(), height = labelImage.getHeight();
            if(width == 0){
                width = 130;
            }
            if(height == 0){
                height = 130;
            }
            Image photo = fileImg.getScaledInstance(width, height,Image.SCALE_SMOOTH);
            ImageIcon imageIcon = new ImageIcon(photo);
            labelImage.setIcon(imageIcon);
        } catch (IOException ex) {
            Logger.getLogger(Beranda.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        jButton1.addActionListener(new ActionListener() {
        public void actionPerformed(ActionEvent e) {
            // call method to retrieve data from database
            }   
        });
    }
    
    // untuk delete data
    public void deleteData() {
        String sql = "DELETE FROM seller WHERE id='"+selectedID+"'";
        int affectedRow = db.updateQuery(sql);
        if (affectedRow > 0) {
            JOptionPane.showMessageDialog(null, "Data berhasil dihapus!");
        } else {
            JOptionPane.showMessageDialog(null, "Data gagal dihapus!");
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtNamaBarang = new javax.swing.JLabel();
        txtHarga = new javax.swing.JLabel();
        txtTerjual = new javax.swing.JLabel();
        txtRating = new javax.swing.JLabel();
        txtUkuran1 = new javax.swing.JLabel();
        txtUkuran2 = new javax.swing.JLabel();
        txtUkuran3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        labelImage = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNamaBarang.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 12)); // NOI18N
        txtNamaBarang.setForeground(new java.awt.Color(255, 255, 255));
        txtNamaBarang.setText("CUTOFF Kemeja Merah Pria Pendek");
        jPanel1.add(txtNamaBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, -1, -1));

        txtHarga.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 10)); // NOI18N
        txtHarga.setForeground(new java.awt.Color(128, 128, 128));
        txtHarga.setText("489.000");
        jPanel1.add(txtHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, -1, -1));

        txtTerjual.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 10)); // NOI18N
        txtTerjual.setForeground(new java.awt.Color(128, 128, 128));
        txtTerjual.setText("110");
        jPanel1.add(txtTerjual, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, 70, 30));

        txtRating.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 10)); // NOI18N
        txtRating.setForeground(new java.awt.Color(128, 128, 128));
        txtRating.setText("4,9");
        jPanel1.add(txtRating, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, -1, -1));

        txtUkuran1.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 10)); // NOI18N
        txtUkuran1.setForeground(new java.awt.Color(128, 128, 128));
        txtUkuran1.setText("Terjual      :");
        jPanel1.add(txtUkuran1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, -1, -1));

        txtUkuran2.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 10)); // NOI18N
        txtUkuran2.setForeground(new java.awt.Color(128, 128, 128));
        txtUkuran2.setText("Harga       :");
        jPanel1.add(txtUkuran2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, -1, -1));

        txtUkuran3.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 10)); // NOI18N
        txtUkuran3.setForeground(new java.awt.Color(128, 128, 128));
        txtUkuran3.setText("Rating      :");
        jPanel1.add(txtUkuran3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, -1, -1));

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Delete");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, -1, -1));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(labelImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 130));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 130, 130));

        jButton2.setBackground(new java.awt.Color(0, 0, 255));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Edit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login (2).png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-9, -4, 430, 150));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:    
        int confirmationPrompt = JOptionPane.showConfirmDialog(this,"Anda yakin ingin mengahapus data?", "Select Delete Option", JOptionPane.YES_NO_OPTION);
        if(confirmationPrompt == JOptionPane.YES_OPTION){
            deleteData();
            Beranda mainFrame = (Beranda) this.getTopLevelAncestor();
            mainFrame.setPanel();  
        }        
      
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        FormUpdate update = new FormUpdate(home,selectedID, nama, harga, rating, terjual,foto);
        update.setLocationRelativeTo(null);
        update.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        // TODO add your handling code here:
        // Get Selected Data

    }//GEN-LAST:event_jPanel1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labelImage;
    private javax.swing.JLabel txtHarga;
    private javax.swing.JLabel txtNamaBarang;
    private javax.swing.JLabel txtRating;
    private javax.swing.JLabel txtTerjual;
    private javax.swing.JLabel txtUkuran1;
    private javax.swing.JLabel txtUkuran2;
    private javax.swing.JLabel txtUkuran3;
    // End of variables declaration//GEN-END:variables
}
